### ISSUE TITLE
Connecting with Smart-on-FHIR in Cerner

### ISSUE THREAD

**Issue by seanmcilvenna** [lhncbc/lforms-fhir-app#18]
I have installed and run the lforms-fhir-app on my own server. I am trying to setup an App in Cerner's Code Console to launch the lforms-fhir-app using Smart-on-FHIR.

I can see that the `iss` and `launch` parameters are getting passed to the lforms-fhir-app... But, the app isn't doing anything with them.

Can you tell me how to configure the app to detect the smart-on-fhir launch and use the auth _and_ fhir server specified in the smart-on-fhir launch context?

I've looked through the fhir.service.js file, and can't see anywhere that deals with the `iss` and `launch` parameters...

**Comment by plynchnlm** [comment]
lforms-fhir-app relies on https://github.com/smart-on-fhir/client-js for the SMART on FHIR authorization process.  A copy of that library is in source/js/fhir-client.js, which uses both the iss and launch parameters.  (I am not sure why we are not pulling it from npm.)  I suggest you check the documentation for that package (http://docs.smarthealthit.org/client-js/#client) and http://docs.smarthealthit.org/client-js/client.html) and if there is something in lforms-fhir-app that needs to change, please let us know.
