### ISSUE TITLE
SMART launch fails because fhirUser is not checked in id token

### ISSUE THREAD

**Issue by atri-dastidar-snkeos** [lhncbc/lforms-fhir-app#19]
We are trying to launch the app hosted at https://lhcforms.nlm.nih.gov/lforms-fhir-app/launch.html with an id token which has the fhirUser claim but not the profile claim. [The fhirUser claim is the preferred claim for the SMART launch standard](http://hl7.org/fhir/smart-app-launch/scopes-and-launch-context.html).

However, [since only the profile claim is checked](https://github.com/lhncbc/lforms-fhir-app/blob/master/source/js/fhir-client.js#L11251):
```
_proto.getFhirUser = function getFhirUser() {
    var idToken = this.getIdToken();

    if (idToken) {
      return idToken.profile;
    }

    return null;
  }
```

the launch fails with the error "User is not available".

This is already fixed in the [latest version of fhir-client.js](https://docs.smarthealthit.org/client-js/):
```
_proto.getFhirUser = function getFhirUser() {
    var idToken = this.getIdToken();

    if (idToken) {
      // Epic may return a full url
      // @see https://github.com/smart-on-fhir/client-js/issues/105
      if (idToken.fhirUser) {
        return idToken.fhirUser.split("/").slice(-2).join("/");
      }

      return idToken.profile;
    }

    return null;
  }
```

We would appreciate if the fhir-client in this repo can also be updated to the latest version.

**Comment by plynchnlm** [comment]
Thanks for the report and the helpful code excerpt.  Updated fhirclient to 2.4.0.
