### ISSUE TITLE
FHIR's ethnicity and race codesystems not loading

### ISSUE THREAD

**Issue by vadi2** [lhncbc/lforms-fhir-app#22]
Making use of HL7's valueset for ethnicity and race for some odd reason does not work. LHCforms renders the question without the expected dropdown:

<img width="847" alt="Screenshot 2022-05-30 at 7 59 17 AM" src="https://user-images.githubusercontent.com/110988/170926850-be9bd868-40d6-49f4-94a9-d3ab1a6a2ac1.png">

It does make the correct request to expand the valueset and receives a proper-looking response back:

<img width="1505" alt="Screenshot 2022-05-30 at 7 51 21 AM" src="https://user-images.githubusercontent.com/110988/170926932-8ffa13dd-fb62-4cb8-96e7-0e06d1a01c06.png">

What could be going wrong?

The Questionnaire is currently available in the LHCForms sandbox server for any patient as 'Patient reported response at baseline', also attached below for posterity:
[Bundle-DebugBundlePatient-01-Baseline.json.zip](https://github.com/lhncbc/lforms-fhir-app/files/8795833/Bundle-DebugBundlePatient-01-Baseline.json.zip)

**Comment by plynchnlm** [comment]
LHC-Forms expects contained ValueSets to have an "expansion".  It does not generate expansions on its own for contained ValueSets.

Sorry for the long delay on this.  Somehow I missed the alert for this issue.  Feel free to contact me on chat.fhir.org if that happens.

**Comment by vadi2** [comment]
By a contained valueset you mean a valueset embedded within a Questionnaire? 

That is not the case here if so, so the issue might be something else.

**Comment by plynchnlm** [comment]
I thought they were contained, but now I see they are just in the bundle.  Let me take another look.

**Comment by plynchnlm** [comment]
The problem is that the race and ethnicity questions are of type "string".  They need to be either "choice" or "open-choice".

**Comment by vadi2** [comment]
That would explain it! Sorry about the trouble.

**Comment by plynchnlm** [comment]
No problem.
