### ISSUE TITLE
Connect the SDC Questionnaire App to a FHIR Server which is protected by OAuth 2.0 server [Keycloak](https://www.keycloak.org/)

### ISSUE THREAD

**Issue by muhammad-levi** [lhncbc/lforms-fhir-app#31]
Salaam, Hi,

Could you please help (or guide me the possible steps) to make the SDC Questionnaire App able to connect to the FHIR Server which is protected by OAuth 2.0 server [Keycloak](https://www.keycloak.org/)?

The test FHIR Server is available at https://hapi-fhir.dev.sid-indonesia.org/

Thank you.

**Comment by plynchnlm** [comment]
It can connect to a server that supports SMART on FHIR (http://www.hl7.org/fhir/smart-app-launch/), which is based on OAuth, but I don't know whether it would work with a plain OAuth server.  You might take a look at the discussion here:  https://chat.fhir.org/#narrow/stream/179170-smart/topic/Keycloak.20for.20SMART.20authz .
