### ISSUE TITLE
`answerValueset`-type answers are not filled in on QR load

### ISSUE THREAD

**Issue by vadi2** [lhncbc/lforms-fhir-app#33]
Saving a Questionnaire with answers that are of type `answerValueset` and then loading a QuestionnaireResponse back does not seem to work - the answer does not get populated.

answerOptions work fine though, and that is what all of the example questionnaires seem to be using.

Example Questionnaire:

```json
{
  "resourceType": "Questionnaire",
  "title": "Test",
  "status": "draft",
  "item": [
    {
      "type": "choice",
      "linkId": "662775593708",
      "text": "Does it work?",
      "answerValueSet": "http://hl7.org/fhir/ValueSet/yesnodontknow"
    }
  ]
}
```

Demo:

[Screen recording 2023-04-10 2.21.05 PM.webm](https://user-images.githubusercontent.com/110988/230901036-d070a488-0061-4c4a-95f3-fe0be937a309.webm)

**Comment by plynchnlm** [comment]
Thanks for this report.  I suspect it is a bug in the lforms package.  We will be giving this high priority.

**Comment by vadi2** [comment]
Thank you! Prepopulation also doesn't work in this case, I suspect the root reason is similar.

**Comment by plynchnlm** [comment]
Yes, most likely.  Thanks for the update.

**Comment by lhcye** [comment]
lforms v33.3.4 has the fix for the aforementioned bug. I have updated lforms-fhir-app with the lforms v33.3.4. Please try it out again (https://lhcforms.nlm.nih.gov/sdc) and let us know if there is any problems. Thanks.
