### ISSUE TITLE
Importing patient data directly to the questionnaire respons

### ISSUE THREAD

**Issue by annabel-uzl** [lhncbc/lforms-fhir-app#35]
I would like to be able to import patient data directly to the form. 
For example, if the questionnaire handles Hard Coronary Heart Disease and some of the questions are about blood pressure, Cholesterol, ... it would be handy to import this data instead of manually typing them over. 

My suggestion would be to being able to import these data as FHIR resources, take over de data forget about the linkage (at least for now, to not make it too complicated). I see this as a change in the app - not the form builder.

I understand this would be a big change as the app would need to be able to read from various FHIR resources.
Is this something you see as usefull and possible? I'm looking into using this app in our hospital in Belgium and I need to explore a bit more myself, but if I would use it, I would be very happy to help making this change possible.

**Comment by plynchnlm** [comment]
Various mechanisms for importing patient data are discussed in the Structured Data Capture Implementation guide (see the [main page](https://build.fhir.org/ig/HL7/sdc/) and the [Form Population](https://build.fhir.org/ig/HL7/sdc/populate.html) sections).  The LHC-Forms widget (used by lforms-fhir-app) supports a subset of those approaches.  For examples in the demo at https://lhcforms.nlm.nih.gov/sdc, under the "Featured Questionnaires" section, try the "US Surgeon General family health portrait" and "Weight & Height tracking panel" forms.  Those cover prepopulation both from the Patient resource and from the patient's Observations, as well the use of various Expression extensions to compute values.

**Comment by annabel-uzl** [comment]
Ah okay, i didn't know, thanks for clearifying. I'll close this issue :)
