### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by jonathandick** [lhncbc/lforms-fhir-app#8]
Hey, i'm writing on behalf of OpenMRS (github.com/openmrs). We're interested in potentially integrating a version of this into the EMR. I'd love to have a conversation with whoever is leading the LHC Forms effort to better understand your roadmap and future support. Thanks!

**Comment by plynchnlm** [comment]
Hi-- that would probably be me.  I am the technical lead of the LHC-Forms project.  Feel free to contact me at plynch@nih.gov.
